// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'fullWidth': string;
  'fullWidthButton': string;
  'label': string;
  'wrap': string;
  'wrapButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
