// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tooltip': string;
  'tooltipCenter': string;
  'tooltipLeft': string;
  'tooltipRight': string;
}
export const cssExports: CssExports;
export default cssExports;
