// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'darkStyle': string;
  'disabled': string;
  'icon': string;
  'input': string;
  'label': string;
  'lightStyle': string;
  'textarea': string;
  'tooltip': string;
  'withIcon': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
