// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  darkStyle: string;
  input: string;
  label: string;
  lightStyle: string;
  textarea: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
