// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adjustSection': string;
  'adjustSectionChildren': string;
  'adjustSectionTitle': string;
  'card': string;
  'direction': string;
  'header': string;
  'input': string;
  'inputButton': string;
  'newCard': string;
  'section': string;
  'space': string;
  'spaceBetween': string;
}
export const cssExports: CssExports;
export default cssExports;
