// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'autoapply': string;
  'header': string;
  'icon': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
