// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  darkStyle: string;
  disabled: string;
  icon: string;
  input: string;
  lightStyle: string;
  text: string;
  tooltip: string;
}
export const cssExports: CssExports;
export default cssExports;
