// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  header_name: string;
  input: string;
  section: string;
  space: string;
}
export const cssExports: CssExports;
export default cssExports;
