// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  input: string;
  inputGroup: string;
  name: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
